name: Build and Deploy LaTeX HTML and PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        run: |
          apt update && apt upgrade -y

      - name: Install Node.js
        run: |
          apt install -y nodejs npm

      - name: Build HTML from LaTeX
        run: |
          make4ht -c html.cfg -d html main.tex && mv html/main.html html/index.html

      - name: Build PDF from LaTeX
        run: |
          mkdir pdf
          pdflatex -interaction=nonstopmode -halt-on-error -output-directory=pdf main.tex
          biber pdf/main.aux
          biber pdf/main.aux
          pdflatex -interaction=nonstopmode -halt-on-error -output-directory=pdf main.tex
          pdflatex -interaction=nonstopmode -halt-on-error -output-directory=pdf main.tex

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: html/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: pdf/main.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: html
          path: html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          target_branch: gh-pages

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf
          path: pdf/

      - name: Create or update "continuous" release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: continuous
          name: Continuous Release
          draft: false
          prerelease: true
          files: pdf/main.pdf
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

